# Python Django - WEB
# django-repro-app devops pipeline

trigger:
- master
- development

pool:
  vmImage: 'ubuntu-20.04'
strategy:
  matrix:
    Python38:
      PYTHON_VERSION: '3.8'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: 1

- task: AzureRmWebAppDeployment@4
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  displayName: 'Deploy to Production'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '7c7c43d0-0b58-4674-bd10-eb4032952fd5'
    appType: 'webAppLinux'
    ResourceGroupName: '2104140060004041-django-repro-rg'
    WebAppName: 'django-repro-app'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: 'PYTHON|3.8'
    AppSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT "True"'

- task: AzureRmWebAppDeployment@4
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'development'))
  displayName: 'Deploy to Development'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '7c7c43d0-0b58-4674-bd10-eb4032952fd5'
    appType: 'webAppLinux'
    WebAppName: 'django-repro-app'
    deployToSlotOrASE: true
    ResourceGroupName: '2104140060004041-django-repro-rg'
    SlotName: 'dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: 'PYTHON|3.8'
    AppSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT "True"'